# Taken from https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

combine_control_expr = true
format_code_in_doc_comments = true
normalize_comments = true
trailing_semicolon = true
use_field_init_shorthand = true
force_multiline_blocks = true
hex_literal_case = "Upper"
imports_granularity = "Crate"
group_imports = "One"
